services:
  - type: web
    name: halleyx-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        value: mongodb://localhost:27017
      - key: DATABASE_NAME
        value: dashbuilder
